LANG = {
    'en': {
        'import_files': 'Import Files',
        'selected_files': 'Selected Files:',
        'audio_player': 'Audio Player:',
        'recommended_cuts': 'Recommended Cuts',
        'edit_cut': 'Edit Cut:',
        'start': 'Start',
        'end': 'End',
        'set_from_player': 'Set from Player',
        'restore_recommended': 'Restore Recommended',
        'export_selected': 'Export Selected',
        'cancel': 'Cancel',
        'status_ready': 'Status: Ready',
        'app_title': 'Taraweeh Cutter',
        'language': 'EN',
        'not_implemented': 'Not implemented yet',
        'welcome': 'Welcome to Taraweeh Cutter!',
        'example_button': 'Click Me',
        'info': 'Info',
        'button_clicked_message': 'Button was clicked!',
        'status_button_clicked': 'Status: Button clicked',
    },
    'ar': {
        'import_files': 'استيراد الملفات',
        'selected_files': ':الملفات المختارة',
        'audio_player': ':مشغل الصوت',
        'recommended_cuts': 'المقاطع المقترحة',
        'edit_cut': ':تعديل المقطع',
        'start': 'البداية',
        'end': 'النهاية',
        'set_from_player': 'تحديد من المشغل',
        'restore_recommended': 'استعادة المقترح',
        'export_selected': 'تصدير المحدد',
        'cancel': 'إلغاء',
        'status_ready': 'جاهز',
        'app_title': 'مقسّم التراويح',
        'language': 'AR',
        'not_implemented': 'لم يتم التنفيذ بعد',
        'welcome': 'مرحبًا بك في مقسّم التراويح!',
        'example_button': 'اضغط هنا',
        'info': 'معلومات',
        'button_clicked_message': 'تم الضغط على الزر!',
        'status_button_clicked': 'تم الضغط على الزر',
    }
}
