LANG = {
    'en': {
        'app_title': 'Taraweeh Cutter',
        'theme': 'Theme',
        'language': 'العربية',

        'files': 'Files',
        'import_files': 'Import Files',
        'import_folder': 'Import Folder',
        'select_all': 'Select all',
        'filename_col': 'Name',
        'status_col': 'Status',

        'waveform': 'Waveform',
        'play': 'Play',
        'pause': 'Pause',
        'start': 'Start',
        'end': 'End',
        'set_begin': 'Set begin',
        'set_end': 'Set end',
        'add_cut': 'Add segment',
        'skip_silence': 'Skip silence',
        'prev_silence': 'Previous silence',
        'next_silence': 'Next silence',
        'split_here': 'Split here',
        'remove_segment': 'Remove (make silence)',
        'create_segment': 'Create segment here',
        'merge_title': 'Merge segments',
        'merge_prompt': 'Merge these two segments into one?',

        'cuts': 'Segments',
        'analyze': 'Analyze',
        'remove_cut': 'Remove',
        'restore_recommended': 'Restore recommended',
        'source': 'Source',
        'auto': 'auto',
        'manual': 'manual',
        'export_col': 'Export',

        'export_selected': 'Export Selected',
        'ready': 'Ready',

        'advanced': 'Advanced',
        'silence_threshold': 'Silence threshold',
        'min_silence': 'Min silence length',
        'min_segment_length': 'Min segment length',
        'save': 'Save',
        'settings_saved': 'Settings saved',
        'settings_invalid': 'Invalid settings — check the values',
        'tip_silence_threshold': 'Audio quieter than this level counts as silence. A lower value (e.g. −40 dB) treats only very quiet parts as gaps; a higher value (e.g. −20 dB) treats more as silence, producing more (and smaller) segments.',
        'tip_min_silence': 'A quiet stretch must last at least this long to split the recording. Increase it to ignore short pauses within the recitation.',
        'tip_min_segment_length': 'Detected voice segments shorter than this are discarded, so brief sounds do not become segments.',

        'imported_n': 'Imported {n} audio file(s)',
        'no_audio_found': 'No supported audio files found',
        'no_selection': 'Select at least one file first',
        'no_cuts': 'No segments to export',
        'analyzing': 'Analyzing {name}…',
        'analyzed_n': 'Found {n} segment(s)',
        'exporting': 'Exporting {i}/{n}…',
        'export_done': 'Exported {n} segment(s) to {dir}',
        'export_failed': 'Export failed: {error}',
        'select_output_dir': 'Choose output folder',
        'ffmpeg_missing': 'ffmpeg not found — analysis, waveform and export are disabled. Install ffmpeg to enable them.',
        'no_audio_backend': 'No audio backend — playback disabled (install pygame). Scrubbing still places markers.',
        'invalid_cut': 'Invalid segment: begin must come before end',
        'preparing_playback': 'Preparing playback…',
        'playback_failed': 'Could not prepare playback for this file',
    },
    'ar': {
        'app_title': 'مُقسِّم التراويح',
        'theme': 'السمة',
        'language': 'English',

        'files': 'الملفات',
        'import_files': 'استيراد ملفات',
        'import_folder': 'استيراد مجلد',
        'select_all': 'تحديد الكل',
        'filename_col': 'الاسم',
        'status_col': 'الحالة',

        'waveform': 'الموجة الصوتية',
        'play': 'تشغيل',
        'pause': 'إيقاف مؤقت',
        'start': 'البداية',
        'end': 'النهاية',
        'set_begin': 'تعيين البداية',
        'set_end': 'تعيين النهاية',
        'add_cut': 'إضافة مقطع',
        'skip_silence': 'تخطّي الصمت',
        'prev_silence': 'الصمت السابق',
        'next_silence': 'الصمت التالي',
        'split_here': 'تقسيم هنا',
        'remove_segment': 'حذف (تحويل إلى صمت)',
        'create_segment': 'إنشاء مقطع هنا',
        'merge_title': 'دمج المقاطع',
        'merge_prompt': 'دمج هذين المقطعين في مقطع واحد؟',

        'cuts': 'المقاطع',
        'analyze': 'تحليل',
        'remove_cut': 'حذف',
        'restore_recommended': 'استعادة المقترح',
        'source': 'المصدر',
        'auto': 'تلقائي',
        'manual': 'يدوي',
        'export_col': 'تصدير',

        'export_selected': 'تصدير المحدد',
        'ready': 'جاهز',

        'advanced': 'إعدادات متقدمة',
        'silence_threshold': 'عتبة الصمت',
        'min_silence': 'أدنى مدة صمت',
        'min_segment_length': 'أدنى طول للمقطع',
        'save': 'حفظ',
        'settings_saved': 'تم حفظ الإعدادات',
        'settings_invalid': 'إعدادات غير صالحة — تحقق من القيم',
        'tip_silence_threshold': 'الصوت الأخفض من هذا المستوى يُعدّ صمتًا. القيمة الأقل (مثل −40 د.ب) تعتبر الأجزاء الهادئة جدًا فقط فواصل؛ والقيمة الأعلى (مثل −20 د.ب) تعتبر المزيد صمتًا فتنتج مقاطع أكثر وأصغر.',
        'tip_min_silence': 'يجب أن تدوم فترة الصمت هذه المدة على الأقل لتقسيم التسجيل. زِدها لتجاهل الوقفات القصيرة أثناء التلاوة.',
        'tip_min_segment_length': 'المقاطع الصوتية الأقصر من هذا الطول تُهمَل، حتى لا تتحول الأصوات القصيرة إلى مقاطع.',

        'imported_n': 'تم استيراد {n} ملف صوتي',
        'no_audio_found': 'لا توجد ملفات صوتية مدعومة',
        'no_selection': 'اختر ملفًا واحدًا على الأقل',
        'no_cuts': 'لا توجد مقاطع للتصدير',
        'analyzing': 'جارٍ تحليل {name}…',
        'analyzed_n': 'تم إيجاد {n} مقطع',
        'exporting': 'جارٍ التصدير {i}/{n}…',
        'export_done': 'تم تصدير {n} مقطع إلى {dir}',
        'export_failed': 'فشل التصدير: {error}',
        'select_output_dir': 'اختر مجلد الإخراج',
        'ffmpeg_missing': 'لم يتم العثور على ffmpeg — التحليل والموجة والتصدير معطّلة. ثبّت ffmpeg لتفعيلها.',
        'no_audio_backend': 'لا يوجد محرك صوت — التشغيل معطّل (ثبّت pygame). لا يزال بإمكانك وضع العلامات.',
        'invalid_cut': 'مقطع غير صالح: يجب أن تسبق البداية النهاية',
        'preparing_playback': 'جارٍ تحضير التشغيل…',
        'playback_failed': 'تعذّر تحضير تشغيل هذا الملف',
    },
}
